### ISSUE TITLE
Please add travis ci support

### ISSUE THREAD

**Issue by danmarsden** [samuelcalegari/moodle-mod_mirotranslate#3]
Some of the tests run by the Moodle.org plugins db can be run via travis-ci on each commit in your github repo. Enabling Travis integration helps you to make sure future changes to your plugin will continue to follow the guidelines.

More information on this is here:
https://moodle.org/mod/forum/discuss.php?d=323384

but the short version:
grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to:
https://travis-ci.org/profile/YOUR_GITHUB_USERNAME
Flick the switch for this repo.

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

something else you might want to change:
in .travis.yml the default file has this line:

env:
global:

MOODLE_BRANCH=MOODLE_38_STABLE
you might want to add other branches to that list - so you might want to change it something like:

env:
global:
MOODLE_BRANCH=MOODLE_35_STABLE
MOODLE_BRANCH=MOODLE_36_STABLE
MOODLE_BRANCH=MOODLE_37_STABLE

**Comment by samuelcalegari** [comment]
I have enabled travis on my github repo.
however i got an errror during build in a mustache template
 `Bad value “” for attribute “src” on element “iframe”: Must be non-empty`
because i use a variable inside ...
 `<iframe class="embed-responsive-item" title="{{title}}" src="{{url}}" allowfullscreen></iframe>`

**Comment by danmarsden** [comment]
Note - not all of those will block approval in the plugins db - just something you might want to look at in future.

I do find the mustache ones a bit of a pain myself sometimes - you can tell travis to ignore a mustache file like this when you know it's ok:
https://github.com/danmarsden/moodle-mod_attendance/blob/main/.travis.yml#L23

obviously that wouldn't work if you were trying to get code into the core Moodle release, but it's in a plugin so it's really up to you. :-)

**Comment by samuelcalegari** [comment]
solved.
Thanks
